#!/bin/bash
set -ex
# mkdir "/content"
ln -sfT "/home/${USER}" "/content"
# ln -s "/home/${USER}/" "/"
# mv "/${USER}" "/content"
# jupyter labextension install @eddienko/jupyterlab-colabinspired-codecellbtn \
#                              @eddienko/jupyterlab-colabinspired-theme-light \
#                              imjoy-jupyter-extension \
#                              @jupyterlab/toc @jupyterlab/git

# rm /opt/anaconda3/share/jupyter/lab/settings

# conda install -c conda-forge jupyterlab-snippets
