#!/bin/bash
set -ex
# mkdir "/content"
ln -sfT "/home/${USER}" "/content"
# ln -s "/home/${USER}/" "/"
# mv "/${USER}" "/content"
# jupyter labextension install @eddienko/jupyterlab-colabinspired-codecellbtn \
#                              @eddienko/jupyterlab-colabinspired-theme-light \
#                              imjoy-jupyter-extension \
#                              @jupyterlab/toc @jupyterlab/git

# rm /opt/anaconda3/share/jupyter/lab/settings

# conda install -c conda-forge jupyterlab-snippets

# export LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/cuda-11.1/lib64:$LD_LIBRARY_PATH

# ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1 \
#     && echo "/usr/local/cuda/lib64/stubs" > /etc/ld.so.conf.d/z-cuda-stubs.conf \
#     && ldconfig

