dict_manifest_to_version = {
                    'Notebook_Augmentor_ZeroCostDL4Mic': 'Augmentor' ,
                    'Notebook_CARE_2D_ZeroCostDL4Mic': 'CARE (2D)' ,
                    'Notebook_CARE_3D_ZeroCostDL4Mic': 'CARE (3D)' ,
                    'Notebook_Cellpose_2D_ZeroCostDL4Mic': 'Cellpose' ,
                    'Notebook_CycleGAN_2D_ZeroCostDL4Mic': 'CycleGAN' ,
                    'Notebook_DFCAN_ZeroCostDL4Mic': 'DFCAN 2D' ,
                    'Notebook_DRMIME_ZeroCostDL4Mic': 'DRMIME' ,
                    'Notebook_DecoNoising_2D_ZeroCostDL4Mic': 'DecoNoising' ,
                    'Notebook_Deep-STORM_2D_ZeroCostDL4Mic': 'Deep-STORM' ,
                    'Notebook_Deep-STORM_2D_ZeroCostDL4Mic_DeepImageJ': 'Deep-STORM BioimageIO' ,
                    'Notebook_DenoiSeg_2D_ZeroCostDL4Mic': 'DenoiSeg' ,
                    'Notebook_Detectron2_ZeroCostDL4Mic': 'Detectron 2D' ,
                    'Notebook_EmbedSeg_2D_ZeroCostDL4Mic': 'EmbedSeg 2D' ,
                    'Notebook_Interactive_Segmentation_Kaibu_2D_ZeroCostDL4Mic': 'Kaibu' ,
                    'Notebook_MaskRCNN_ZeroCostDL4Mic': 'MaskRCNN' ,
                    'Notebook_Noise2Void_2D_ZeroCostDL4Mic': 'Noise2Void (2D)' ,
                    'Notebook_Noise2Void_3D_ZeroCostDL4Mic': 'Noise2Void (3D)' ,
                    'Notebook_Quality_Control_ZeroCostDL4Mic': 'Quality_control' ,
                    'Notebook_RCAN_3D_ZeroCostDL4Mic': '3D RCAN' ,
                    'Notebook_RetinaNet_ZeroCostDL4Mic': 'RetinaNet' ,
                    'Notebook_SplineDist_2D_ZeroCostDL4Mic': 'SplineDist (2D)' ,
                    'Notebook_StarDist_2D_ZeroCostDL4Mic': 'StarDist 2D' ,
                    'Notebook_StarDist_3D_ZeroCostDL4Mic': 'StarDist 3D' ,
                    'Notebook_U-Net_2D_ZeroCostDL4Mic': 'U-Net (2D)', 
                    'Notebook_U-Net_2D_multilabel_ZeroCostDL4Mic': 'U-Net (2D) multilabel',
                    'Notebook_U-Net_3D_ZeroCostDL4Mic': 'U-Net (3D)' ,
                    'Notebook_YOLOv2_ZeroCostDL4Mic': 'YOLOv2' ,
                    'Notebook_fnet_2D_ZeroCostDL4Mic': 'fnet (2D)' ,
                    'Notebook_fnet_3D_ZeroCostDL4Mic': 'fnet (3D)' ,
                    'Notebook_pix2pix_2D_ZeroCostDL4Mic': 'pix2pix' ,
                    'WGAN_ZeroCostDL4Mic.ipynb': 'WGAN 2D',
                    }

dict_dl4miceverywhere_to_manifest = {
    'CARE_2D_DL4Mic': 'Notebook_CARE_2D_ZeroCostDL4Mic',
    'CARE_3D_DL4Mic': 'Notebook_CARE_3D_ZeroCostDL4Mic',
    'Cellpose_2D_DL4Mic': 'Notebook_Cellpose_2D_ZeroCostDL4Mic',
    'CycleGAN_DL4Mic': 'Notebook_CycleGAN_2D_ZeroCostDL4Mic',
    'DFCAN_DL4Mic': 'Notebook_DFCAN_ZeroCostDL4Mic',
    'DRMIME_2D_DL4Mic': 'Notebook_DRMIME_ZeroCostDL4Mic',
    'DecoNoising_2D_DL4Mic': 'Notebook_DecoNoising_2D_ZeroCostDL4Mic',
    'Deep-STORM_2D_DL4Mic': 'Notebook_Deep-STORM_2D_ZeroCostDL4Mic',
    'DenoiSeg_DL4Mic': 'Notebook_DenoiSeg_2D_ZeroCostDL4Mic',
    'Detectron2_2D_DL4Mic': 'Notebook_Detectron2_ZeroCostDL4Mic',
    'Embedseg_DL4Mic': 'Notebook_EmbedSeg_2D_ZeroCostDL4Mic',
    'MaskRCNN_DL4Mic': 'Notebook_MaskRCNN_ZeroCostDL4Mic',
    'Noise2Void_2D_DL4Mic': 'Notebook_Noise2Void_2D_ZeroCostDL4Mic',
    'Noise2Void_3D_DL4Mic': 'Notebook_Noise2Void_3D_ZeroCostDL4Mic',
    '3D-RCAN_DL4Mic': 'Notebook_RCAN_3D_ZeroCostDL4Mic',
    'RetinaNet_DL4Mic': 'Notebook_RetinaNet_ZeroCostDL4Mic',
    'SplineDist_2D_DL4Mic': 'Notebook_SplineDist_2D_ZeroCostDL4Mic',
    'StarDist_2D_DL4Mic': 'Notebook_StarDist_2D_ZeroCostDL4Mic',
    'StarDist_3D_DL4Mic': 'Notebook_StarDist_3D_ZeroCostDL4Mic',
    'U-Net_2D_DL4Mic': 'Notebook_U-Net_2D_ZeroCostDL4Mic',
    'U-Net_2D_Multilabel_DL4Mic': 'Notebook_U-Net_2D_multilabel_ZeroCostDL4Mic',
    'U-Net_3D_DL4Mic': 'Notebook_U-Net_3D_ZeroCostDL4Mic',
    'YOLOv2_DL4Mic': 'Notebook_YOLOv2_ZeroCostDL4Mic',
    'fnet_2D_DL4Mic': 'Notebook_fnet_2D_ZeroCostDL4Mic',
    'fnet_3D_DL4Mic': 'Notebook_fnet_3D_ZeroCostDL4Mic',
    'pix2pix_DL4Mic': 'Notebook_pix2pix_2D_ZeroCostDL4Mic',
    'WGAN_DL4Mic': 'WGAN_ZeroCostDL4Mic.ipynb',
}

dict_dl4miceverywhere_to_version = {dl4mic_name: dict_manifest_to_version[dict_dl4miceverywhere_to_manifest[dl4mic_name]] for dl4mic_name in dict_dl4miceverywhere_to_manifest.keys()}
