dict_manifest_to_version = {
    'light-swimsuit': 'Augmentor',
    'fun-high-heels': 'CARE (2D)',
    'opalescent-ribbon': 'CARE (3D)',
    'polished-t-shirt': 'Cellpose',
    'flattering-bikini': 'CycleGAN',
    'mesmerizing-shoe': 'DFCAN 2D',
    'playful-scarf': 'Diffusion model for SMLM',
    'irresistible-swimsuit': 'DRMIME',
    'flexible-helmet': 'DecoNoising',
    'inspiring-sandal': 'Deep-STORM',
    'silky-shorts': 'Deep-STORM BioimageIO',
    'smooth-safety-vest': 'DenoiSeg',
    'convenient-t-shirt': 'Detectron 2D',
    'smooth-graduation-hat': 'EmbedSeg 2D',
    'timeless-running-shirt': 'Kaibu',
    'regal-ribbon': 'MaskRCNN',
    'brisk-scarf': 'Noise2Void (2D)',
    'cozy-hiking-boot': 'Noise2Void (3D)',
    'lively-t-shirt': 'Quality_control',
    'striking-necktie': '3D RCAN',
    'convenient-purse': 'RetinaNet',
    'uplifting-backpack': 'SplineDist (2D)',
    'exciting-backpack': 'StarDist 2D',
    'cheerful-cap': 'StarDist 3D',
    'resplendent-ribbon': 'U-Net (2D)',
    'whimsical-helmet': 'U-Net (2D) multilabel',
    'joyful-top-hat': 'U-Net (3D)',
    'bold-shorts': 'YOLOv2',
    'limited-edition-crown': 'fnet (2D)',
    'authoritative-ballet-shoes': 'fnet (3D)',
    'fluid-glasses': 'pix2pix',
    'slinky-bikini': 'WGAN 2D'
}

dict_dl4miceverywhere_to_manifest = {
    'CARE_2D_DL4Mic': 'fun-high-heels',
    'CARE_3D_DL4Mic': 'opalescent-ribbon',
    'Cellpose_2D_DL4Mic': 'polished-t-shirt',
    'CycleGAN_DL4Mic': 'flattering-bikini',
    'DFCAN_DL4Mic': 'mesmerizing-shoe',
    'Diffusion_SMLM_DL4Mic': 'playful-scarf',
    'DRMIME_2D_DL4Mic': 'irresistible-swimsuit',
    'DecoNoising_2D_DL4Mic': 'flexible-helmet',
    'Deep-STORM_2D_DL4Mic': 'inspiring-sandal',
    'DenoiSeg_DL4Mic': 'smooth-safety-vest',
    'Detectron2_2D_DL4Mic': 'convenient-t-shirt',
    'Embedseg_DL4Mic': 'smooth-graduation-hat',
    'MaskRCNN_DL4Mic': 'regal-ribbon',
    'Noise2Void_2D_DL4Mic': 'brisk-scarf',
    'Noise2Void_3D_DL4Mic': 'cozy-hiking-boot',
    '3D-RCAN_DL4Mic': 'striking-necktie',
    'RetinaNet_DL4Mic': 'convenient-purse',
    'SplineDist_2D_DL4Mic': 'uplifting-backpack',
    'StarDist_2D_DL4Mic': 'exciting-backpack',
    'StarDist_3D_DL4Mic': 'cheerful-cap',
    'U-Net_2D_DL4Mic': 'resplendent-ribbon',
    'U-Net_2D_Multilabel_DL4Mic': 'whimsical-helmet',
    'U-Net_3D_DL4Mic': 'joyful-top-hat',
    'YOLOv2_DL4Mic': 'bold-shorts',
    'fnet_2D_DL4Mic': 'limited-edition-crown',
    'fnet_3D_DL4Mic': 'authoritative-ballet-shoes',
    'pix2pix_DL4Mic': 'fluid-glasses',
    'WGAN_DL4Mic': 'slinky-bikini'
}

dict_dl4miceverywhere_to_version = {dl4mic_name: dict_manifest_to_version[dict_dl4miceverywhere_to_manifest[dl4mic_name]] for dl4mic_name in dict_dl4miceverywhere_to_manifest.keys()}
