# Updates the version from all the notebooks on manifest.bioimage.io.yaml 
#using the versions from Latest_Notebook_versions.csv

name: Update versions on the manifest
on:
  workflow_dispatch:

jobs:
  update_configuration:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install requirements
        run: pip install -r Tools/CI_requirements.txt
      - name: Update the manifest
        run: python3 Tools/update_manifest_versioning.py
      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: GitHub Action - Update manifest versioning
