name: Validate Collection

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  run:
    name: Validate manifest.bioimage.io.yaml 
    runs-on: ubuntu-latest
    steps:
    - name: Clone ZeroCostDL4Mic
      uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install bioimageio.spec
      run: pip install bioimageio.spec lxml
    - name: Validate collection manifest
      run: bioimageio validate-partner-collection manifest.bioimage.io.yaml
